### ISSUE TITLE
Conda Env Error

### ISSUE THREAD

**Issue by bbarad** [eugenepalovcak/restore#1]
When I try to generate the conda env using restore.yml I get the following error:

```
Solving environment: failed

ResolvePackageNotFound: 
  - qt==5.9.7=h52cfd70_1
```

I am using anaconda3.

**Comment by eugenepalovcak** [comment]
Lol. Hey Ben, sorry this isn't quite ready for prime time, but I did update the yml file. The problem was very specific package names. I have more general package names now, so it should work.

**Comment by bbarad** [comment]
Thanks, this update resolves my installation issue. I am comfortable running with the knowledge that its not ready for prime time; hopefully any issues I find will be helpful in getting it ready.
